### ISSUE TITLE
cm15.new never returns error

### ISSUE THREAD

**Issue by Sjeanpierre** [rightscale/rsc#6]
I am trying to use this library as a go package and I have run into a few issues. the first one seems to be related to the fact that no matter what I provide the new function it always returns without any error.

```go
	username := "useremail@email.com"
	password := "userpass"
	auth := rsapi.LoginAuthenticator{Username: username, Password: password}
	accountId := 3456
	endPoint := "us-3.rightscale.com"
	client, error := cm15.New(accountId, endPoint, &auth, nil, nil)
```

How can I tell that my login or credentials are valid?

**Comment by raphael** [comment]
Thank you for the report, the code to check explicitly for the response status code was missing (woops). This is now fixed and the following code snippets illustrates how you can check your credentials:
```go
package main

import (
	"fmt"
	"net/http"

	"github.com/rightscale/rsc/rsapi"
)

func main() {
	username := "useremail@email.com"
	password := "userpass"
	auth := rsapi.LoginAuthenticator{Username: username, Password: password, Client: http.DefaultClient}
	accountId := 3456
	endPoint := "us-3.rightscale.com"
	fmt.Printf("%v\n", auth.Refresh(endPoint, accountId))
}
```
```
$ go run main.go
Authentication failed: 401 Unauthorized
```

**Comment by Sjeanpierre** [comment]
Thank you so much for the quick response! :+1: 

let me know if I can do anything to help with this project, especially around documentation :wink: 

Do you have any sample code of this package being used within a go application? I've been having some trouble getting it to work for me and I seem to learn best when I am able to see some sample code.

**Comment by raphael** [comment]
I've added a very [basic example](https://github.com/rightscale/rsc/tree/master/cm15/examples/basic) that should help you getting started. I did find a couple of issues with the API metadata in the process which I also fixed. As you can tell this is work in progress and I fully expect that we'll find other issues as new code paths are being used. Help is always welcome, the top contenders are more docs, more unit tests and more examples. One area that we'll be focusing on shortly is functional testing so that we can iron out the type of issues that you ran into.

**Comment by Sjeanpierre** [comment]
:+1: Thank you very much for the examples! They will be a great help. I will do my best to put together some examples as I build my solution on top of this package.

**Comment by raphael** [comment]
Awesome, thank you! I'll close this ticket for now, feel free to open new ones if you run into other issues.
